
#ifndef __RTCP_H__
#define __RTCP_H__

namespace RTCP
{
  enum eRequest
    {
      LAUNCH_GAME = 1,
      NETWORK_CONNECTED = 2,
      NETWORK_DISCONNECTED = 3,
      ERROR_REQUEST_SUCCESS = 101,
      ERROR_USER_REFUSE = 201,
      ERROR_USER_NOT_RESPOND = 202,
      ERROR_USER_FAIL_TO_CONNECT = 203,
      ERROR_USER_UNDERSTAND_BUT_REFUSE = 204,
      ERROR_SEVER_FAIL_PROCESS = 301,
      ERROR_SERVER_REFUSE_COMMAND = 302,
      ERROR_SERVER_UNDERSTAND_BUT_REFUSE = 303,
      ERROR_INVALID_REQUEST = 401,
      ERROR_INCOMPLETE_REQUEST = 402,
      ERROR_FORBIDDEN_REQUEST = 403,
      ERROR_REQUEST_NOT_FOUND = 404,
      ROOM_GET_LIST = 1101,
      ROOM_JOIN = 1102,
      ROOM_CREATE = 1103,
      ROOM_LEAVE = 1104,
      ROOM_READY = 1105,
      ROOM_CONNECTION_READY = 1106,
      ROOM_LIST = 1201,
      ROOM_NOTIFY_JOIN = 1202,
      ROOM_NOTIFY_PLAYER = 1203,
      ROOM_NOTIFY_READY = 1204,
      ROOM_SEND_RESSOURCES = 1205,
      ROOM_START_GAME = 1206,
      GAME_MOVE = 2101,
      GAME_START_SHOT = 2102,
      GAME_LAUNCH_SHOT = 2103,
      GAME_LAUNCH_BONUS = 2104,
      GAME_PLAYER_SPAWN = 2201,
      GAME_PLAYER_MOVE = 2202,
      GAME_PLAYER_DESTROY = 2203,
      GAME_ENEMY_SPAWN = 2204,
      GAME_ENEMY_MOVE = 2205,
      GAME_ENEMY_DESTROY = 2206,
      GAME_BULLET_SPAWN = 2207,
      GAME_BULLET_MOVE = 2208,
      GAME_BULLET_DESTROY = 2209,
      GAME_BONUS_SPAWN = 2210,
      GAME_BONUS_PICKED = 2211,
      GAME_NOTIFY_END = 2212,
	  GAME_PAUSE,
	  GAME_RESUME,
	  LAST,
    };

}

#endif
